plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.11'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Source: https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.1'
}


javafx {
    version = "26.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}


// Tell the jar which class has your main() method
jar {
    manifest {
        attributes 'Main-Class': 'net.wady.Launcher'
    }
}

application {
    mainClass = 'net.wady.Launcher'
}


test {
    useJUnitPlatform()
}

